version: "3.1"
services:
    php:
      build: ./docker
      image: terry-api-php
      container_name: terry-api
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
    php8:
      build:
        context: ./docker
        dockerfile: Dockerfile.php8
      image: terry-api-php8
      container_name: terry-api-php8
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
