version: "3.1"
services:
    php:
      build: docker
      image: terry-api-php
      container_name: terry-api
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
