version: "3.1"
services:
    php:
      build:
        context: ./docker
        dockerfile: Dockerfile.php74
      image: rest-php74
      container_name: rest-php74
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
    php8:
      build:
        context: ./docker
        dockerfile: Dockerfile.php80
      image: rest-php80
      container_name: rest-php80
      working_dir: /app
      env_file:
        - ./docker/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
